version: "3.8"

services:
  web-dev:
    build:
      context: ./client-manager-web
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client-manager-web:/app
    restart: unless-stopped

  api-dev:
    build:
      context: ./client-manager-api
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - ./client-manager-api:/app
